### ISSUE TITLE
Echo Api is returning response in HTML <DOCTYPE) format; not JSON

### ISSUE THREAD

**Issue by hbray** [ghballiet/echo-api#3] opened 2015-06-21 04:25 UTC
Installed the latest version on my Raspberry PI/node.js; Configuration/setup seems ok; However, when connection to echo.amazon.com the api/echo/index.js fails at line 64 trying to parse a json response; the response is in HTML; the request at line 37 is being sent with content-type application/json; but, response still comes back in HTML. Perhaps something with my "Cookie" header is overriding? not sure if thats possible. anyway, can't get beyond the exception of trying to parse HTML as JSON.

**Comment by ghballiet** [comment] 2015-06-22 17:02
I'll see if I can reproduce this issue on my pi. What OS (and version) are you running?

**Comment by ghballiet** [comment] 2015-11-02 18:54
So far, I've been unable to reproduce this issue, so I am closing this for now. If you can send me some additional information I can use for debugging, I'll reopen it.

**Closed as completed by ghballiet** 2015-11-02 18:54 UTC
